### ISSUE TITLE
CSVから自動取得したデータがエラーだった場合のアラート

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#232]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* データのもととなるCSVは役所が作るため、列名やデータの型が勝手に変えられて、正常にデータを更新できない可能性がある
* 自動取得にエラーがあった場合、それを知らせるアラートが必要ではないか

**Comment by Kanahiro** [comment]
全然コードにはなっていないですが、現在考えている実装は以下です。

- 読み込んだデータが正常かチェックする
- もし異常があれば、jsonを出力しない

つまりアラートではなく、異常が発生以後はjsonデータが更新されなくなる仕組みで良いかな、と考えています（正常だった頃の最後のデータが残る）。

しかし

> 読み込んだデータが正常かチェックする

が課題で、しかも今後は行政担当者がデータを入力するとなると、そのバリデーションはそれなりの困難が予想されます。

**Comment by daisuke-fukuda** [comment]
> もし異常があれば、jsonを出力しない

基本この方針で、なぜエラーだったのか、Slackあたりに通知がくると気がつくことができるのでいいな、と思いました！
GitHubActionからSlack通知するというのをやった事があります。

コピペですがこんな感じです。

```
      # 失敗したら通知
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: build # default: 8398a7@action-slack
          text: build failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
```

> が課題で、しかも今後は行政担当者がデータを入力するとなると、そのバリデーションはそれなりの困難が予想されます。

これは悩ましいですねぇ。
まずは

- keyが勝手に変わっていないか
- 値のフォーマットが（定義できるところだけ）変わっていないか

あたりでしょうか、、、
